spellername = "Farefare"
spellerversion = "0.1.0"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Farefare spellchecker"
gur = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Farefare, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
gur = "TRANSLATE: A spellchecker for Farefare, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.gur"

[windows]
system_product_code = "{7CC18B9D-D513-4820-9FE2-172451CBF6FB}_is1"
