template = "https://github.com/giellalt/template-lang-und"
rev_id = 283
template_sha = "bfef967c632b9041975725ec13da8c2dfe66b74e"

[replacements]
__GLOTTOLOG_ID__ = "fare1241"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-gur"
__UND2C__ = "gur"
__UNDEFINED__ = "Farefare"
__UND__ = "gur"
