template = "https://github.com/giellalt/template-lang-und"
rev_id = 312
template_sha = "aaa43738ed413bb95e9bd39f5489b35bab88cc4b"

[replacements]
__GLOTTOLOG_ID__ = "fare1241"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-gur"
__UND2C__ = "gur"
__UNDEFINED__ = "Farefare"
__UND__ = "gur"
