template = "https://github.com/giellalt/template-lang-und"
rev_id = 298
template_sha = "4822abccfb9b3ce82bf2876217cde02b5f647d14"

[replacements]
__GLOTTOLOG_ID__ = "fare1241"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-gur"
__UND2C__ = "gur"
__UNDEFINED__ = "Farefare"
__UND__ = "gur"
